### ISSUE TITLE
Something went wrong. Please try again

### ISSUE THREAD

**Issue by AashriyaTechnology** [quintuslabs/GroceryStore-with-server#3]
when im try to add item using cms panel . then error as **Something went wrong. Please try again**
please resolve this problem

**Comment by quintuslabs** [comment]
Thank you for using our repositary. I will check and  and revert you back.

Happy Coding
Quintus Labs

**Comment by quintuslabs** [comment]
Already fixed you can check now

**Comment by quintuslabs** [comment]
Please Check if u find any issue please re open issue
