### ISSUE TITLE
Beautiful App

### ISSUE THREAD

**Issue by SunnyforJava** [quintuslabs/GroceryStore-with-server#6]
Salute to u team.
A very beautiful eye catching work.

**Comment by NomanBaigA** [comment]
Hi bro. @SunnyforJava I want admin panel username or password for grocery store app. if you have then please give me. Please help me bro.

**Comment by NomanBaigA** [comment]
when i use localhost it also want username or password for admin panel. Please Help Me.

**Comment by Manick94** [comment]
> when i use localhost it also want username or password for admin panel. Please Help Me.

Go into PHPMyAdmin --> Find your Database (grocery) --> Click on the "admin" table --> click "Edit" to edit the admin table --> in the Password section select "MD5" from the dropdown  -- put a new new password in the field --> click on "Go" --> then use the updated username and password...

**Comment by CharlieBrownie99** [comment]
Hello! How can I connect the Android App to Xampp?

**Comment by NomanBaigA** [comment]
> > when i use localhost it also want username or password for admin panel. Please Help Me.
> 
> Go into PHPMyAdmin --> Find your Database (grocery) --> Click on the "admin" table --> click "Edit" to edit the admin table --> in the Password section select "MD5" from the dropdown -- put a new new password in the field --> click on "Go" --> then use the updated username and password...

Thank you very much sir. @Manick94

**Comment by NomanBaigA** [comment]
Thank you very much sir @Manick94

**Comment by santoshnet** [comment]
run xampp-> upload your serverfile to htdocs directory -> create a database -> change configuration-> import .sql file in your database-> check your ip address in your pc/laptop  => app/src/main/java/com/quintus/labs/grocerystore/api/clients/RestClient.java=>  public static final String BASE_URL = http://ipaddress/directoryname;

**Comment by iamsj7** [comment]
i uploaded server files on 000webhost and connected the database, affter loging in with admin password dashboard shows blank screen
(white screen)

i updated the username, and password of database in api folder config file too 

Warning: session_start(): Cannot start session when headers already sent in /storage/ssd5/929/14303929/public_html/grocery/admin/dashboard.php on line 8
﻿
